/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteBeneficiosRouteImport } from './routes/_site.beneficios'
import { Route as SiteComoFuncionaRouteImport } from './routes/_site.como-funciona'
import { Route as SiteRegioesRouteImport } from './routes/_site.regioes'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBeneficiosRoute = SiteBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => SiteRoute,
} as any)
const SiteComoFuncionaRoute = SiteComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRegioesRoute = SiteRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/beneficios': typeof SiteBeneficiosRoute
  '/como-funciona': typeof SiteComoFuncionaRoute
  '/regioes': typeof SiteRegioesRoute
}
export interface FileRoutesByTo {
  '/beneficios': typeof SiteBeneficiosRoute
  '/como-funciona': typeof SiteComoFuncionaRoute
  '/regioes': typeof SiteRegioesRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/beneficios': typeof SiteBeneficiosRoute
  '/_site/como-funciona': typeof SiteComoFuncionaRoute
  '/_site/regioes': typeof SiteRegioesRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beneficios' | '/como-funciona' | '/regioes'
  fileRoutesByTo: FileRoutesByTo
  to: '/beneficios' | '/como-funciona' | '/regioes' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/beneficios'
    | '/_site/como-funciona'
    | '/_site/regioes'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/beneficios': {
      id: '/_site/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof SiteBeneficiosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/como-funciona': {
      id: '/_site/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof SiteComoFuncionaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/regioes': {
      id: '/_site/regioes'
      path: '/regioes'
      fullPath: '/regioes'
      preLoaderRoute: typeof SiteRegioesRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteBeneficiosRoute: typeof SiteBeneficiosRoute
  SiteComoFuncionaRoute: typeof SiteComoFuncionaRoute
  SiteRegioesRoute: typeof SiteRegioesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBeneficiosRoute: SiteBeneficiosRoute,
  SiteComoFuncionaRoute: SiteComoFuncionaRoute,
  SiteRegioesRoute: SiteRegioesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
