/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteBeneficiosRouteImport } from './routes/_site.beneficios'
import { Route as SiteComoFuncionaRouteImport } from './routes/_site.como-funciona'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteObrigadoRouteImport } from './routes/_site.obrigado'
import { Route as SitePerguntasFrequentesRouteImport } from './routes/_site.perguntas-frequentes'
import { Route as SitePoliticaDePrivacidadeRouteImport } from './routes/_site.politica-de-privacidade'
import { Route as SiteRegioesRouteImport } from './routes/_site.regioes'
import { Route as SiteSolicitarCotacaoRouteImport } from './routes/_site.solicitar-cotacao'
import { Route as SiteTermosDeUsoRouteImport } from './routes/_site.termos-de-uso'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmTarefasRouteImport } from './routes/app.crm.tarefas'
import { Route as AppDemoLeadsRouteImport } from './routes/app.demo.leads'
import { Route as AppSettingsSiteContentRouteImport } from './routes/app.settings.site-content'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBeneficiosRoute = SiteBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => SiteRoute,
} as any)
const SiteComoFuncionaRoute = SiteComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteObrigadoRoute = SiteObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => SiteRoute,
} as any)
const SitePerguntasFrequentesRoute = SitePerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => SiteRoute,
} as any)
const SitePoliticaDePrivacidadeRoute =
  SitePoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => SiteRoute,
  } as any)
const SiteRegioesRoute = SiteRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSolicitarCotacaoRoute = SiteSolicitarCotacaoRouteImport.update({
  id: '/solicitar-cotacao',
  path: '/solicitar-cotacao',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermosDeUsoRoute = SiteTermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => SiteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmTarefasRoute = AppCrmTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppDemoLeadsRoute = AppDemoLeadsRouteImport.update({
  id: '/demo/leads',
  path: '/demo/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSiteContentRoute = AppSettingsSiteContentRouteImport.update({
  id: '/settings/site-content',
  path: '/settings/site-content',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/beneficios': typeof SiteBeneficiosRoute
  '/como-funciona': typeof SiteComoFuncionaRoute
  '/contato': typeof SiteContatoRoute
  '/obrigado': typeof SiteObrigadoRoute
  '/perguntas-frequentes': typeof SitePerguntasFrequentesRoute
  '/politica-de-privacidade': typeof SitePoliticaDePrivacidadeRoute
  '/regioes': typeof SiteRegioesRoute
  '/solicitar-cotacao': typeof SiteSolicitarCotacaoRoute
  '/termos-de-uso': typeof SiteTermosDeUsoRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
  '/app/crm/tarefas': typeof AppCrmTarefasRoute
  '/app/demo/leads': typeof AppDemoLeadsRoute
  '/app/settings/site-content': typeof AppSettingsSiteContentRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof AuthLoginRoute
  '/beneficios': typeof SiteBeneficiosRoute
  '/como-funciona': typeof SiteComoFuncionaRoute
  '/contato': typeof SiteContatoRoute
  '/obrigado': typeof SiteObrigadoRoute
  '/perguntas-frequentes': typeof SitePerguntasFrequentesRoute
  '/politica-de-privacidade': typeof SitePoliticaDePrivacidadeRoute
  '/regioes': typeof SiteRegioesRoute
  '/solicitar-cotacao': typeof SiteSolicitarCotacaoRoute
  '/termos-de-uso': typeof SiteTermosDeUsoRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
  '/app/crm/tarefas': typeof AppCrmTarefasRoute
  '/app/demo/leads': typeof AppDemoLeadsRoute
  '/app/settings/site-content': typeof AppSettingsSiteContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_site/beneficios': typeof SiteBeneficiosRoute
  '/_site/como-funciona': typeof SiteComoFuncionaRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/obrigado': typeof SiteObrigadoRoute
  '/_site/perguntas-frequentes': typeof SitePerguntasFrequentesRoute
  '/_site/politica-de-privacidade': typeof SitePoliticaDePrivacidadeRoute
  '/_site/regioes': typeof SiteRegioesRoute
  '/_site/solicitar-cotacao': typeof SiteSolicitarCotacaoRoute
  '/_site/termos-de-uso': typeof SiteTermosDeUsoRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/crm/tarefas': typeof AppCrmTarefasRoute
  '/app/demo/leads': typeof AppDemoLeadsRoute
  '/app/settings/site-content': typeof AppSettingsSiteContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/beneficios'
    | '/como-funciona'
    | '/contato'
    | '/obrigado'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/regioes'
    | '/solicitar-cotacao'
    | '/termos-de-uso'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/'
    | '/app/crm/tarefas'
    | '/app/demo/leads'
    | '/app/settings/site-content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/beneficios'
    | '/como-funciona'
    | '/contato'
    | '/obrigado'
    | '/perguntas-frequentes'
    | '/politica-de-privacidade'
    | '/regioes'
    | '/solicitar-cotacao'
    | '/termos-de-uso'
    | '/app/crm'
    | '/app/dashboard'
    | '/app'
    | '/app/crm/tarefas'
    | '/app/demo/leads'
    | '/app/settings/site-content'
  id:
    | '__root__'
    | '/_auth'
    | '/_site'
    | '/app'
    | '/_auth/login'
    | '/_site/beneficios'
    | '/_site/como-funciona'
    | '/_site/contato'
    | '/_site/obrigado'
    | '/_site/perguntas-frequentes'
    | '/_site/politica-de-privacidade'
    | '/_site/regioes'
    | '/_site/solicitar-cotacao'
    | '/_site/termos-de-uso'
    | '/app/crm'
    | '/app/dashboard'
    | '/_site/'
    | '/app/'
    | '/app/crm/tarefas'
    | '/app/demo/leads'
    | '/app/settings/site-content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/beneficios': {
      id: '/_site/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof SiteBeneficiosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/como-funciona': {
      id: '/_site/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof SiteComoFuncionaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/obrigado': {
      id: '/_site/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof SiteObrigadoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/perguntas-frequentes': {
      id: '/_site/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof SitePerguntasFrequentesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/politica-de-privacidade': {
      id: '/_site/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof SitePoliticaDePrivacidadeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/regioes': {
      id: '/_site/regioes'
      path: '/regioes'
      fullPath: '/regioes'
      preLoaderRoute: typeof SiteRegioesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/solicitar-cotacao': {
      id: '/_site/solicitar-cotacao'
      path: '/solicitar-cotacao'
      fullPath: '/solicitar-cotacao'
      preLoaderRoute: typeof SiteSolicitarCotacaoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/termos-de-uso': {
      id: '/_site/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof SiteTermosDeUsoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/tarefas': {
      id: '/app/crm/tarefas'
      path: '/tarefas'
      fullPath: '/app/crm/tarefas'
      preLoaderRoute: typeof AppCrmTarefasRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/app/demo/leads': {
      id: '/app/demo/leads'
      path: '/demo/leads'
      fullPath: '/app/demo/leads'
      preLoaderRoute: typeof AppDemoLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/site-content': {
      id: '/app/settings/site-content'
      path: '/settings/site-content'
      fullPath: '/app/settings/site-content'
      preLoaderRoute: typeof AppSettingsSiteContentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SiteRouteChildren {
  SiteBeneficiosRoute: typeof SiteBeneficiosRoute
  SiteComoFuncionaRoute: typeof SiteComoFuncionaRoute
  SiteContatoRoute: typeof SiteContatoRoute
  SiteObrigadoRoute: typeof SiteObrigadoRoute
  SitePerguntasFrequentesRoute: typeof SitePerguntasFrequentesRoute
  SitePoliticaDePrivacidadeRoute: typeof SitePoliticaDePrivacidadeRoute
  SiteRegioesRoute: typeof SiteRegioesRoute
  SiteSolicitarCotacaoRoute: typeof SiteSolicitarCotacaoRoute
  SiteTermosDeUsoRoute: typeof SiteTermosDeUsoRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBeneficiosRoute: SiteBeneficiosRoute,
  SiteComoFuncionaRoute: SiteComoFuncionaRoute,
  SiteContatoRoute: SiteContatoRoute,
  SiteObrigadoRoute: SiteObrigadoRoute,
  SitePerguntasFrequentesRoute: SitePerguntasFrequentesRoute,
  SitePoliticaDePrivacidadeRoute: SitePoliticaDePrivacidadeRoute,
  SiteRegioesRoute: SiteRegioesRoute,
  SiteSolicitarCotacaoRoute: SiteSolicitarCotacaoRoute,
  SiteTermosDeUsoRoute: SiteTermosDeUsoRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppCrmRouteChildren {
  AppCrmTarefasRoute: typeof AppCrmTarefasRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmTarefasRoute: AppCrmTarefasRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppRouteChildren {
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemoLeadsRoute: typeof AppDemoLeadsRoute
  AppSettingsSiteContentRoute: typeof AppSettingsSiteContentRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCrmRoute: AppCrmRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemoLeadsRoute: AppDemoLeadsRoute,
  AppSettingsSiteContentRoute: AppSettingsSiteContentRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
